export default {
  list: [{
    id: 0,
    node_id: '--------------',
    name: '--------------',
    full_name: '--------------',
    html_url: '--------------',
    description: '--------------',
    stargazers_count: 0,
    watchers_count: 0,
    forks_count: 240,
    open_issues_count: 5,
    language: '--------------',
    owner: {
      login: '---------',
      id: 0,
      node_id: '---------',
      avatar_url: 'https://avatars.dicebear.com/v2/male/f2a72d0ca3a0fc4b5b25095859845ab2.svg',
      gravatar_id: '',
      url: '----------',
      html_url: '--------------',
      followers_url: '-----------------',
      following_url: '----------------------',
      gists_url: '---------------------------',
      starred_url: '--------------------------------',
      subscriptions_url: '----------------------------',
      organizations_url: '------------------------------',
      repos_url: '---------------------------',
      events_url: '---------------------------',
      received_events_url: '---------------------------',
      type: '---------------------------',
      site_admin: false,
      score: 1.0,
    },
  }],
  meta: {
    page: 1,
    total: null,
  },
};
